name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      # - name: Install system dependencies
      #   run: sudo apt-get install -y texlive-latex-base texlive-latex-extra context python3-tk
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov tikzplotlib --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest' }}
